export const APP_NAME = "Quakescape";
export const APP_TAGLINE = "Geospatial risk intelligence for seismic response";
export const ACCENT_COLOR = "#2DD4BF";
export const API_TIMEOUT_MS = 15000;
export const DEFAULT_RADIUS_KM = 50;
export const DEFAULT_LIMIT = 25;
export const DEFAULT_COMPARE_LIMIT = 4;
export const DEFAULT_TIMELINE_DAYS = 30;
export const DEFAULT_HEATMAP_GRID = 6;
